#!/usr/bin/env python3
"""Cluster interconnect calibration harness for DHIR.

Evaluates inter-node network characteristics across cluster topologies:
  1. Profiles point-to-point master-worker links (0 <-> b) via asymmetric ping-pong
     (payload transfer with one-way acknowledgment latency compensation).
  2. Measures collective communicator MPI_Barrier latency.
  3. Benchmarks serialized hub gather and broadcast patterns generated by DHIR.
  4. Validates the star communication model sum_i (alpha_i + beta_i * bytes) against
     measured collective timings.
  5. Serializes link metrics and barrier costs into system_config.calibrated.json.
"""

import argparse
import json
import os
import statistics
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DRIVER = Path(__file__).resolve().parent / "drivers" / "cluster_calibration_main.cc"
PROFILES_DIR = Path(__file__).resolve().parent / "profiles"
DEFAULT_SIZES = [8, 1024, 32768, 262144, 1048576, 4194304, 16777216]


def med(values):
    vals = [v for v in values if v is not None]
    return statistics.median(vals) if vals else None


def cov(values):
    vals = [v for v in values if v is not None]
    if len(vals) < 2:
        return 0.0
    mean = statistics.mean(vals)
    return statistics.pstdev(vals) / mean if mean else 0.0


def parse_rows(text):
    """Parses CLUSTERCAL output lines into record categories, preserving raw timing records."""
    rows = {k: [] for k in ("node", "link", "incast", "hubgather", "hubbcast",
                            "libbcast", "barrier")}
    for line in text.splitlines():
        if not line.startswith("CLUSTERCAL,"):
            continue
        parts = line.strip().split(",")
        kind = parts[1]
        if kind in rows:
            rows[kind].append(parts[2:])
    return rows


def build_driver(workdir, mpicxx="mpicxx"):
    """Compiles the network calibration C++ benchmark driver into the designated work directory."""
    workdir.mkdir(parents=True, exist_ok=True)
    binary = workdir / "cluster_calibration"
    cmd = [mpicxx, "-O2", "-std=c++17", str(DRIVER), "-o", str(binary)]
    proc = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)
    if proc.returncode != 0:
        raise RuntimeError(f"driver build failed:\n{proc.stderr[-2000:]}")
    return binary


def fit_link(symmetric, asymmetric_fwd, asymmetric_rev=None):
    """Fits link parameters (alpha, beta, sustained bandwidth) from a message size sweep.

    Applies asymmetric ping-pong timings compensated for one-way ACK delay.
    Latency alpha reflects the median of latency-bound transfers (<= 4 KB).
    Inverse bandwidth beta is calculated as the secant across maximal payload sizes.
    """
    asym = asymmetric_fwd
    sizes = sorted(asym)
    ack = asym[sizes[0]] / 2.0
    msg = {b: max(ack, asym[b] - ack) for b in sizes}
    small = [t for b, t in msg.items() if b <= 4096]
    alpha = med(small) if small else msg[sizes[0]]

    beta = 0.0
    if len(sizes) >= 2:
        b1, b2 = sizes[-2], sizes[-1]
        if b2 > b1:
            beta = max(0.0, (msg[b2] - msg[b1]) / (b2 - b1))

    # Linear regression check to compute R^2 goodness-of-fit
    pts = [(b, msg[b]) for b in sizes]
    r2 = 1.0
    if len(pts) >= 3:
        xs = [x for x, _ in pts]
        ys = [y for _, y in pts]
        xm, ym = statistics.mean(xs), statistics.mean(ys)
        den = sum((x - xm) ** 2 for x in xs)
        slope = sum((x - xm) * (y - ym) for x, y in pts) / den if den else 0.0
        icept = ym - slope * xm
        sst = sum((y - ym) ** 2 for y in ys)
        sse = sum((y - (icept + slope * x)) ** 2 for x, y in pts)
        r2 = 1.0 - sse / sst if sst else 1.0

    bandwidth = (1.0 / beta) if beta > 0.0 else None

    # Calculate reverse transmission parameters if reverse samples exist
    rev_alpha, rev_beta, rev_bw = None, None, None
    if asymmetric_rev:
        r_ack = asymmetric_rev[sizes[0]] / 2.0
        r_msg = {b: max(r_ack, asymmetric_rev[b] - r_ack) for b in sizes}
        r_small = [t for b, t in r_msg.items() if b <= 4096]
        rev_alpha = med(r_small) if r_small else r_msg[sizes[0]]
        if len(sizes) >= 2 and sizes[-1] > sizes[-2]:
            rev_beta = max(0.0, (r_msg[sizes[-1]] - r_msg[sizes[-2]]) / (sizes[-1] - sizes[-2]))
            rev_bw = (1.0 / rev_beta) if rev_beta > 0.0 else None

    return {
        "alpha_seconds": alpha,
        "beta_seconds_per_byte": beta,
        "bandwidth_byte_per_second": bandwidth,
        "ols_r_squared": r2,
        "estimator": "asymmetric ping-pong minus one-way ack latency",
        "reverse_alpha_seconds": rev_alpha,
        "reverse_beta_seconds_per_byte": rev_beta,
        "reverse_bandwidth_byte_per_second": rev_bw,
        "message_cost_seconds": {str(b): msg[b] for b in sizes},
        "symmetric_one_way_seconds": {str(b): symmetric[b] for b in sizes} if symmetric else {}
    }


def classify_topology(links, nranks):
    """Determines fabric uniformity based on variance across spoke link metrics."""
    alphas = [link["alpha_seconds"] for link in links.values()]
    betas = [link["beta_seconds_per_byte"] for link in links.values()]
    bws = [link["bandwidth_byte_per_second"] for link in links.values() if link["bandwidth_byte_per_second"]]

    alpha_cov_val = cov(alphas)
    beta_cov_val = cov(betas)

    # Classify fabric as non-uniform if latency coefficient of variation exceeds 25%
    is_uniform = alpha_cov_val <= 0.25 and beta_cov_val <= 0.25
    physical = "uniform_fabric" if is_uniform else "non_uniform_fabric"
    detail = ("every inter-node link has uniform alpha and beta within spread: flat switched fabric"
              if is_uniform else
              f"inter-node links exhibit significant latency spread (alpha CoV: {alpha_cov_val:.1%}): asymmetric fabric")

    return {
        "physical": physical,
        "physical_detail": detail,
        "logical": "star_rooted_at_rank_0",
        "logical_detail": ("DHIR gathers and broadcasts sequentially through rank 0, "
                          "so communication cost is the sum of spoke transfers."),
        "ranks": nranks,
        "inter_node": {
            "spokes": len(links),
            "alpha_median": med(alphas),
            "alpha_cov": alpha_cov_val,
            "beta_median": med(betas),
            "beta_cov": beta_cov_val,
            "bandwidth_median_byte_per_second": med(bws)
        }
    }


def star_model(links, nranks, nbytes):
    """Computes expected collective transfer duration using the serialized star model."""
    spokes = []
    for r in range(1, nranks):
        fit = links.get((0, r)) or links.get((r, 0))
        if fit is None:
            continue
        spokes.append(fit["alpha_seconds"] + fit["beta_seconds_per_byte"] * nbytes)
    if not spokes:
        return None
    return {
        "serialized": sum(spokes),
        "overlapped": max(spokes),
        "spokes": len(spokes)
    }


def validate_star(links, nranks, measured, label, bulk_from_bytes=65536):
    """Compares serialized star model predictions against empirical collective benchmark measurements."""
    out = []
    for nbytes, seconds in sorted(measured.items()):
        model = star_model(links, nranks, nbytes)
        if model is None:
            continue
        pred = model["serialized"]
        err = abs(pred - seconds) / seconds if seconds > 0 else None
        out.append({
            "bytes": nbytes,
            "measured_seconds": seconds,
            "predicted_seconds": pred,
            "absolute_relative_error": err,
            "in_bulk_regime": nbytes >= bulk_from_bytes,
            "overlapped_lower_bound_seconds": model["overlapped"]
        })
    bulk = [x["absolute_relative_error"] for x in out
            if x["in_bulk_regime"] and x["absolute_relative_error"] is not None]
    allpts = [x["absolute_relative_error"] for x in out
              if x["absolute_relative_error"] is not None]
    small = [x for x in out if not x["in_bulk_regime"]]
    return {
        "pattern": label,
        "points": out,
        "bulk_from_bytes": bulk_from_bytes,
        "median_absolute_relative_error": med(bulk) if bulk else med(allpts),
        "median_absolute_relative_error_all_sizes": med(allpts),
        "small_message_offset_seconds":
            med([x["measured_seconds"] - x["predicted_seconds"] for x in small]) if small else None
    }


def calibrated_config(config, links_by_rank, topology, network_summary):
    """Constructs updated system configuration JSON populated with per-node network parameters."""
    out = json.loads(json.dumps(config))
    node_ids = out["cluster"]["node_ids"]

    # Root rank (rank 0)
    root_id = node_ids[0]
    out["nodes"][root_id]["network"] = {
        "is_root": True
    }

    # Worker ranks (1 to P-1)
    for rank in range(1, len(node_ids)):
        node_id = node_ids[rank]
        fit = links_by_rank.get(rank)
        if fit:
            out["nodes"][node_id]["network"] = {
                "alpha_seconds": fit["alpha_seconds"],
                "beta_seconds_per_byte": fit["beta_seconds_per_byte"],
                "bandwidth_byte_per_second": fit["bandwidth_byte_per_second"]
            }
        else:
            out["nodes"][node_id]["network"] = {
                "alpha_seconds": network_summary["alpha_seconds"],
                "beta_seconds_per_byte": network_summary["beta_seconds_per_byte"],
                "bandwidth_byte_per_second": network_summary["bandwidth_byte_per_second"]
            }

    # Cluster-wide summary metrics (medians and barrier latency)
    out["network"] = {
        "alpha_seconds": network_summary["alpha_seconds"],
        "beta_seconds_per_byte": network_summary["beta_seconds_per_byte"],
        "bandwidth_byte_per_second": network_summary["bandwidth_byte_per_second"],
        "barrier_seconds": network_summary["barrier_seconds"]
    }
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config",
                    default=os.environ.get("DHIR_CLUSTER_CONFIG", str(ROOT / "system_config.json")),
                    help="input system config path")
    ap.add_argument("--workdir",
                    default=os.environ.get("DHIR_CLUSTER_WORKDIR",
                                           str(ROOT / "build" / "clustercal")),
                    help="shared directory visible to all nodes")
    ap.add_argument("--profile", default=str(PROFILES_DIR / "cluster_profile.json"),
                    help="detailed diagnostic profile output path")
    ap.add_argument("--write-config", default="",
                    help="path for the calibrated output config (default: <config>.calibrated.json)")
    ap.add_argument("--raw", default=str(PROFILES_DIR / "cluster_calibration_raw.csv"),
                    help="raw CSV measurement output path")
    ap.add_argument("--repeats", type=int, default=2,
                    help="number of calibration sweeps")
    ap.add_argument("--net-iters", type=int, default=60,
                    help="iterations per payload size in ping-pong and collectives")
    ap.add_argument("--net-warmups", type=int, default=10,
                    help="warmup iterations before timing")
    ap.add_argument("--sizes", nargs="+", type=int, default=DEFAULT_SIZES,
                    help="payload sizes in bytes")
    ap.add_argument("--mpirun", default=os.environ.get("MPIRUN", "mpirun"),
                    help="mpirun command path")
    ap.add_argument("--mpicxx", default=os.environ.get("MPICXX", "mpicxx"),
                    help="mpicxx compiler path")
    ap.add_argument("--mpirun-flags", default=os.environ.get("DHIR_MPIRUN_FLAGS", ""),
                    help="extra flags for mpirun (e.g. --map-by ppr:1:node --bind-to none)")
    ap.add_argument("--timeout", type=int, default=1800,
                    help="timeout in seconds for calibration run")
    ap.add_argument("--max-star-error", type=float, default=0.25,
                    help="maximum allowed median error of the star collective prediction")
    args = ap.parse_args()

    config_path = Path(args.config)
    config = json.loads(config_path.read_text())
    node_ids = config["cluster"]["node_ids"]
    world = int(config["cluster"]["world_size"])
    if world != len(node_ids):
        ap.error(f"world_size {world} != len(node_ids) {len(node_ids)}")

    workdir = Path(args.workdir)
    binary = build_driver(workdir, args.mpicxx)

    cmd = [args.mpirun]
    if args.mpirun_flags:
        cmd += args.mpirun_flags.split()
    cmd += ["-np", str(world), str(binary),
            str(args.net_iters), str(args.net_warmups),
            str(args.repeats)] + [str(s) for s in args.sizes]

    print(f"launching: {' '.join(cmd)}", flush=True)
    proc = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True, timeout=args.timeout)
    if proc.returncode != 0:
        sys.stderr.write(f"cluster calibration error: rc={proc.returncode}:\n{proc.stderr}\n")
        return 2

    # Write raw CSV records
    Path(args.raw).parent.mkdir(parents=True, exist_ok=True)
    Path(args.raw).write_text(proc.stdout)

    rows = parse_rows(proc.stdout)
    if not rows["node"]:
        raise RuntimeError("driver emitted no node records")

    # Collect node placement metadata
    ranks = []
    for r in range(world):
        facts = [x for x in rows["node"] if int(x[1]) == r]
        if not facts:
            raise RuntimeError(f"rank {r} produced no node record")
        last = facts[-1]
        ranks.append({
            "rank": r,
            "host": last[2],
            "local_rank": int(last[3]),
            "local_size": int(last[4]),
            "node_index": int(last[5])
        })

    # Aggregate spoke link measurements
    links_raw = {}
    for r in rows["link"]:
        # rep, a, b, bytes, iters, sym, asymF, [asymR]
        a, b = int(r[1]), int(r[2])
        nbytes = int(r[3])
        sym = float(r[5])
        asym_fwd = float(r[6])
        asym_rev = float(r[7]) if len(r) > 7 else asym_fwd
        pair = (a, b)
        entry = links_raw.setdefault(pair, {"sym": {}, "asym_fwd": {}, "asym_rev": {}})
        entry["sym"].setdefault(nbytes, []).append(sym)
        entry["asym_fwd"].setdefault(nbytes, []).append(asym_fwd)
        entry["asym_rev"].setdefault(nbytes, []).append(asym_rev)

    # Fit linear model for each spoke link
    links = {}
    links_by_rank = {}
    for (a, b), data in links_raw.items():
        sym_med = {nb: med(vals) for nb, vals in data["sym"].items()}
        asym_fwd_med = {nb: med(vals) for nb, vals in data["asym_fwd"].items()}
        asym_rev_med = {nb: med(vals) for nb, vals in data["asym_rev"].items()}
        fit = fit_link(sym_med, asym_fwd_med, asym_rev_med)
        fit["a"] = a
        fit["b"] = b
        fit["host"] = ranks[b]["host"] if b < len(ranks) else f"rank{b}"
        links[(a, b)] = fit
        if a == 0:
            links_by_rank[b] = fit

    # Aggregate collective benchmark records
    collectives = {}
    for kind in ("incast", "hubgather", "hubbcast", "libbcast"):
        points_sync, points_pipe = {}, {}
        for r in rows[kind]:
            # rep, root, bytes, iters, sync, pipe
            nbytes = int(r[2])
            sync_val = float(r[4])
            pipe_val = float(r[5])
            points_sync.setdefault(nbytes, []).append(sync_val)
            points_pipe.setdefault(nbytes, []).append(pipe_val)
        collectives[kind] = {
            "sync": {nb: med(vals) for nb, vals in sorted(points_sync.items())},
            "pipelined": {nb: med(vals) for nb, vals in sorted(points_pipe.items())}
        }

    barriers = [float(r[2]) for r in rows["barrier"]]
    barrier_med = med(barriers) if barriers else 0.0

    # Evaluate fabric topology characteristics
    topology = classify_topology(links, world)

    # Validate empirical collectives against star model
    hubgather_sync = collectives.get("hubgather", {}).get("sync", {})
    star_gather = validate_star(links, world, hubgather_sync, "serialized hub gather")

    hubbcast_sync = collectives.get("hubbcast", {}).get("sync", {})
    star_bcast = validate_star(links, world, hubbcast_sync, "serialized hub broadcast")

    star_err = star_gather["median_absolute_relative_error"]
    passed_star = star_err is not None and star_err <= args.max_star_error

    checks = {
        "serialized_star_predicts_hub_gather": {
            "median_absolute_relative_error": star_err,
            "threshold": args.max_star_error,
            "passed": passed_star,
            "barrier_seconds": barrier_med
        }
    }

    network_summary = {
        "alpha_seconds": topology["inter_node"]["alpha_median"],
        "beta_seconds_per_byte": topology["inter_node"]["beta_median"],
        "bandwidth_byte_per_second": topology["inter_node"]["bandwidth_median_byte_per_second"],
        "barrier_seconds": barrier_med
    }

    # Export cluster profile JSON
    profile = {
        "schema_version": 2,
        "scope": "pure network calibration of cluster interconnect and collectives",
        "config": str(config_path.resolve()),
        "world_size": world,
        "node_ids": node_ids,
        "ranks": ranks,
        "network": {
            **network_summary,
            "topology": topology,
            "links": list(links.values()),
            "measured_collectives": {
                "hub_gather": star_gather,
                "hub_broadcast": star_bcast,
                "raw_measurements": collectives
            }
        },
        "gates": checks,
        "passed": passed_star,
        "raw_csv": str(Path(args.raw).resolve())
    }
    Path(args.profile).parent.mkdir(parents=True, exist_ok=True)
    Path(args.profile).write_text(json.dumps(profile, indent=2) + "\n")

    # Export calibrated system configuration
    out_config = Path(args.write_config) if args.write_config else config_path.with_suffix(".calibrated.json")
    calibrated = calibrated_config(config, links_by_rank, topology, network_summary)
    out_config.write_text(json.dumps(calibrated, indent=2) + "\n")

    # Display network calibration summary
    print(f"\nprofile={args.profile}")
    print(f"config ={out_config}")
    print(f"raw    ={args.raw}")
    print(f"\ntopology: physical={topology['physical']} logical={topology['logical']} "
          f"({world} ranks, {len(node_ids)} nodes)")
    print(f"detail  : {topology['physical_detail']}")
    print(f"\nmaster-to-worker spoke links:")
    print(f"  {'spoke':<8} {'host':<20} {'alpha (us)':>12} {'beta (ns/B)':>14} {'bandwidth (MB/s)':>18} {'R^2':>8}")
    for b in range(1, world):
        fit = links_by_rank.get(b)
        if fit:
            alpha_us = fit["alpha_seconds"] * 1e6
            beta_ns = fit["beta_seconds_per_byte"] * 1e9
            bw_mb = (fit["bandwidth_byte_per_second"] or 0) / 1e6
            r2 = fit["ols_r_squared"]
            print(f"  0 -> {b:<3} {fit['host']:<20} {alpha_us:>12.2f} {beta_ns:>14.4f} {bw_mb:>18.2f} {r2:>8.4f}")

    print(f"\ncluster synchronization & summary:")
    print(f"  MPI_Barrier latency : {barrier_med*1e6:.2f} us")
    print(f"  median alpha        : {network_summary['alpha_seconds']*1e6:.2f} us")
    print(f"  median bandwidth    : {(network_summary['bandwidth_byte_per_second'] or 0)/1e6:.2f} MB/s")

    print(f"\ncollective verification:")
    print(f"  star model vs hub gather median error: {(star_err or 0):.1%}")
    print(f"  gate check: {'PASS' if passed_star else 'FAIL'} (threshold: {args.max_star_error:.1%})")

    return 0 if passed_star else 1


if __name__ == "__main__":
    sys.exit(main())
